trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=azuredevsecopssonar -Dsonar.projectKey=azuredevsecopssonar_azuredevsecopssonar -Dsonar.login=TOKEN
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipeline"
